nc = str(input('Digite seu nome completo:')).strip().split()
print('Prazer em te conhecer!')
pn = nc[0].capitalize()
un = nc[-1].capitalize()
print(f'Seu primeiro nome é {pn}')
print(f'Seu último nome é {un}')
